---
- name: Install docker & docker-compose
  hosts: all
  become: yes

  vars:
    docker_install_compose: true
    docker_compose_version: "1.25.4"
    docker_pip_version: "4.2.0"
    docker_edition: "ce"
    docker_package: "docker-{{ docker_edition }}-19.03.8"

  roles:
    - install_docker_requirements
    - geerlingguy.docker

  tasks:
    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes


- name: Run docker-compose services
  hosts: all
  become: yes

  tasks:
    - name: Tear down existing services
      docker_compose:
        project_src: /vagrant/
        state: absent

    - name: Create and start services
      docker_compose:
        project_src: /vagrant/
        build: yes
